# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealsApp
  target 'MealsApp' do
     pod 'lottie-ios'
     pod 'youtube-ios-player-helper'
  end

  target 'MealsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MealsAppUITests' do
    # Pods for testing
  end


